cafes = [
    {
        "id": 1,
        "name": "Tostao Cafe y Pan",
        "map_url": "https://goo.gl/maps/RbxwcfTjUhxuiNes8",
        "img_url": "https://runrun.es/wp-content/uploads/2017/10/Tostaocafeypan.jpg",
        "location": "Tv. 55 #98A - 66, Bogotá",
        "seats": "10+",
        "has_toilet": False,
        "has_wifi": False,
        "has_sockets": False,
        "can_take_calls": True,
        "coffee_price": "$3",
        "description": "I like this place. The prices are very low, a lot cheaper than many other cafes. The variety of products is big and most of them are tasty.",
    },
    {
        "id": 2,
        "name": "Pan Pa Ya! Pepe Sierra",
        "map_url": "https://goo.gl/maps/oxHQ9RQXN6ZdFar67",
        "img_url": "https://multiplaza-samantha.s3.amazonaws.com/uploads/post/v4_mobile/10902/v400_400_PanPaya800.jpg",
        "location": "Cra. 11 #116-10, Bogotá",
        "seats": "15+",
        "has_toilet": True,
        "has_wifi": False,
        "has_sockets": False,
        "can_take_calls": True,
        "coffee_price": "$8",
        "description": "Staff here, especially the cooks, are the best in Bogota. extremely friendly and helpful and fast. bunuelos fresh out of the fryer are genuinely mind-blowing.",
    },
    {
        "id": 3,
        "name": "Brot Apice 97",
        "map_url": "https://goo.gl/maps/1kQVjiFeGq5vPoMH9",
        "img_url": "https://static.wixstatic.com/media/e8e56c_3f515c0850864ed0ae44d8c56583e044~mv2_d_2412_1366_s_2.png/v1/fill/w_419,h_230,al_c,q_85,usm_0.66_1.00_0.01/e8e56c_3f515c0850864ed0ae44d8c56583e044~mv2_d_2412_1366_s_2.webp",
        "location": "Cra. 11B # 97, 56, Bogotá",
        "seats": "8",
        "has_toilet": False,
        "has_wifi": True,
        "has_sockets": True,
        "can_take_calls": True,
        "coffee_price": "$15",
        "description": "Highly recommended. Food was delicious and service was great. Very nice spot!",
    },
    {
        "id": 4,
        "name": "BB Banana Bread",
        "map_url": "https://g.page/bbbananabread?share",
        "img_url": "https://bananabananabread.com/wp-content/uploads/2020/07/Banana-Bread-6A1024.jpg",
        "location": "Cl. 90 #11-56, Bogotá",
        "seats": "10+",
        "has_toilet": True,
        "has_wifi": True,
        "has_sockets": False,
        "can_take_calls": True,
        "coffee_price": "$5",
        "description": "Bakery seemingly specializing in multiple varieties of Banana Bread..",
    },
    {
        "id": 5,
        "name": "Old Town Bakery",
        "map_url": "https://goo.gl/maps/cj8pj5dxqKbQAdtD6",
        "img_url": "https://media-cdn.tripadvisor.com/media/photo-s/05/ee/5f/bc/old-town-bakery.jpg",
        "location": "Ac. 100 ##8 A 49, Bogotá",
        "seats": "8",
        "has_toilet": True,
        "has_wifi": False,
        "has_sockets": True,
        "can_take_calls": True,
        "coffee_price": "$4",
        "description": "One of my favorite for coffee and croissants...",
    },
    {
        "id": 6,
        "name": "Starbucks Usaquen",
        "map_url": "https://goo.gl/maps/NCqyUmK4b35VVM5x9",
        "img_url": "https://www.starbucks.com.co/media/93f2675c869445609bc06405ef09b249_tcm86-18572_w1024_n.jpg",
        "location": "Cra. 6a #118-35, Bogotá",
        "seats": "30+",
        "has_toilet": True,
        "has_wifi": True,
        "has_sockets": True,
        "can_take_calls": True,
        "coffee_price": "$5",
        "description": "This one is probably the nicest Starbucks in Bogotá, the mix between the traditional architecture, the nice view of Usaquéns central square, and Starbucks coffee and tea, is just great. ",
    },
    {
        "id": 7,
        "name": "Juan Valdez Café, Prado",
        "map_url": "https://goo.gl/maps/tzy6GyMKD36snYPH8",
        "img_url": "https://cdn.forbes.co/2020/03/Juan-Valdez-1280x720-1.jpg",
        "location": "Cra. 53a #127-27, Bogotá",
        "seats": "20+",
        "has_toilet": True,
        "has_wifi": True,
        "has_sockets": False,
        "can_take_calls": True,
        "coffee_price": "$7",
        "description": "Good place for having a calm coffee time.",
    },
]
