export const CAFE_LIST_REQUEST = 'CAFE_LIST_REQUEST'
export const CAFE_LIST_SUCCESS = 'CAFE_LIST_SUCCESS'
export const CAFE_LIST_FAIL = 'CAFE_LIST_FAIL'

export const CAFE_DETAILS_REQUEST = 'CAFE_DETAILS_REQUEST'
export const CAFE_DETAILS_SUCCESS = 'CAFE_DETAILS_SUCCESS'
export const CAFE_DETAILS_FAIL = 'CAFE_DETAILS_FAIL'

export const CAFE_DELETE_REQUEST = 'CAFE_DELETE_REQUEST'
export const CAFE_DELETE_SUCCESS = 'CAFE_DELETE_SUCCESS'
export const CAFE_DELETE_FAIL = 'CAFE_DELETE_FAIL'
export const CAFE_DELETE_RESET = 'CAFE_DELETE_RESET'

export const CAFE_CREATE_REQUEST = 'CAFE_CREATE_REQUEST'
export const CAFE_CREATE_SUCCESS = 'CAFE_CREATE_SUCCESS'
export const CAFE_CREATE_FAIL = 'CAFE_CREATE_FAIL'
export const CAFE_CREATE_RESET = 'CAFE_CREATE_RESET'

export const CAFE_UPDATE_REQUEST = 'CAFE_UPDATE_REQUEST'
export const CAFE_UPDATE_SUCCESS = 'CAFE_UPDATE_SUCCESS'
export const CAFE_UPDATE_FAIL = 'CAFE_UPDATE_FAIL'
export const CAFE_UPDATE_RESET = 'CAFE_UPDATE_RESET'


export const CAFE_CREATE_REVIEW_REQUEST = 'CAFE_CREATE_REVIEW_REQUEST'
export const CAFE_CREATE_REVIEW_SUCCESS = 'CAFE_CREATE_REVIEW_SUCCESS'
export const CAFE_CREATE_REVIEW_FAIL = 'CAFE_CREATE_REVIEW_FAIL'
export const CAFE_CREATE_REVIEW_RESET = 'CAFE_CREATE_REVIEW_RESET'

export const CAFE_TOP_REQUEST = 'CAFE_TOP_REQUEST'
export const CAFE_TOP_SUCCESS = 'CAFE_TOP_SUCCESS'
export const CAFE_TOP_FAIL = 'CAFE_TOP_FAIL'