# Generated by Django 4.0.2 on 2022-02-04 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_cafe_can_take_calls_alter_cafe_has_sockets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='cafe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.cafe'),
        ),
    ]
