# Generated by Django 4.0.2 on 2022-02-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_review_cafe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='img_url',
            field=models.CharField(blank=True, default='https://images.unsplash.com/photo-1534040385115-33dcb3acba5b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80', max_length=500, null=True),
        ),
    ]
